### ISSUE TITLE
ps_aor contact issue 

### ISSUE THREAD

**Issue by vivek8690** [minoruta/ast_mongo_ts#4]
in mongoose model, there is a data type string is added to contact filed what if I want to add multiple contacts in ps_aor?

**Comment by minoruta** [comment]
It depends on generic pjsip realtime specification, and I guess it will be `contact-string=user1@abc;user2@def` or something like that.

**Comment by vivek8690** [comment]
Thanks, Comma-separated string worked @minoruta
